<?php 
// this file was generated by gulpfile.js within the task makeFontsPreloads 
print( '
<link rel="preload" href="' . $assetsPath . 'fonts/font-awesome/fontawesome-webfont.woff2?v=4.5.0" as="font" type="font/woff2" crossorigin>
' );